workflow:
  rules:
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == 'main'
      when: never
    - if: $CI_COMMIT_BRANCH == "main"
      variables:
        TAG_NAME: apps1
      when: always
    
 
stages:
- deploy
deploy:
  stage: deploy
  tags:
    - ${TAG_NAME}
  script:
  - docker compose down
  - docker rmi ozon_performance_ecom_api-ozon-performance-ecom-api
  - docker rmi ozon_performance_ecom_api-nginx
  - docker compose up -d
