version: "3.8"

services:
  ozon-performance-ecom-api:
    build: .
    restart: always
    container_name: ozon-performance-ecom-api 
    environment:
      TZ: Europe/Moscow
      ECOMRU_PG_DB_NAME: ${ECOMRU_PG_DB_NAME}
      ECOMRU_PG_HOST: ${ECOMRU_PG_HOST}
      ECOMRU_PG_PORT: ${ECOMRU_PG_PORT}
      ECOMRU_PG_USER: ${ECOMRU_PG_USER}
      ECOMRU_PG_PASSWORD: ${ECOMRU_PG_PASSWORD}
      ECOMRU_PG_SSL_MODE: ${ECOMRU_PG_SSL_MODE}
    volumes:
      - /home/get/logs_all//ozon_performance_ecom_api/:/app/logs/

  nginx:
    container_name: nginx-ozon-performance-ecom-api
    build:
      context: ./nginx
      dockerfile: Dockerfile
    depends_on:
      - ozon-performance-ecom-api
    restart: always
    environment:
      - "TZ=Europe/Moscow"
    ports:
      - 8091:80
      - 4441:443
    volumes:
      - /home/get/cert:/app/cert

