swagger: "2.0"
info:
  title: "Ozon Performance API Documentation"
  contact:
    email: "s.fedyushin@ecomru.ru"
  basePath: "/swagger"
paths:
  "/ozonperformance/addgroup":
    post:
tags:
  - groups
#    - add
summary: "Добавить группу"
description: "Метод для создания группы"
consumes:
- "application/json"
produces:
- "application/json"
parameters:
- in: "body"
  name: "body"
  required: true
  schema:
    type: "object"
    properties:
      client_id:
        type: "string"
        example: "123456-7890123456@advertising.performance.ozon.ru"
#      client_secret:
#        type: "string"
#        example: "xxxxxxxxxxxxxxyyyyyyyyyyyyyyyyyyyyyzzzzzzzzzzzzzzzzzzzzzzz1111111111111222222222"
      campaign_id:
        type: "string"
        example: "1234567"
        description: Идентификатор кампании.
      title:
        type: "string"
        example: "abc123"
        description: Название группы (не обязательно)
      stopwords:
        type:
          - array
            - string
        example: ["маркетплейс", "маркет"]
        description: Список стоп-слов (не обязательно)
      phrases:
        type:
          - array
            - string
        example: ["маркетплейс продажи", "яндекс маркет"]
        description: Список поисковых фраз (не обязательно)
      bids_list:
        type:
          - array
            - string
        example: [ "100000000", "200000000" ]
        description: Список ставок поисковых фраз (не обязательно)
      relevance_status:
        type:
          - array
            - string
        example: [ "__", "__" ]
responses:
  200:
    description: "OK"
  400:
    description: "Bad Request"








