swagger: "2.0"
info:
  title: "Ozon Performance API Documentation"
  contact:
    email: "s.fedyushin@ecomru.ru"
  basePath: "/swagger"
paths:
  "/ozonperformance/budget":
    post:
tags:
  - campaigns
#    - edit
summary: "Изменить ограничения дневного бюджета кампании"
description: "Метод для изменения ограничения дневного бюджета кампании"
consumes:
- "application/json"
produces:
- "application/json"
parameters:
- in: "body"
  name: "body"
  required: true
  schema:
    type: "object"
    properties:
      client_id:
        type: "string"
        example: "123456-7890123456@advertising.performance.ozon.ru"
#      client_secret:
#        type: "string"
#        example: "xxxxxxxxxxxxxxyyyyyyyyyyyyyyyyyyyyyzzzzzzzzzzzzzzzzzzzzzzz1111111111111222222222"
      campaign_id:
        type: "string"
        example: "1234567"
        description: Идентификатор кампании.
      daily_budget:
        type: "string"
        example: "550000000"
        description: Ограничение дневного бюджета рекламной кампании. Единица измерения — одна миллионная доля рубля, округляется до копеек.
      exp_str:
        type: "string"
        example: "DAILY_BUDGET"
        enum:
          - "DAILY_BUDGET"
          - "ASAP"
        description: Способ распределения бюджета. DAILY_BUDGET — бюджет равномерно распределяется по дням; ASAP — быстрая открутка, бюджет не ограничен по дням. По умолчанию — DAILY_BUDGET. (не обязательно)
responses:
  200:
    description: "OK"
  400:
    description: "Bad Request"
