swagger: "2.0"
info:
  title: "Ozon Performance API Documentation"
  contact:
    email: "s.fedyushin@ecomru.ru"
  basePath: "/swagger"
paths:
  "/ozonperformance/delproducts":
    post:
tags:
  - product
    - edit
summary: "Удалить товары из кампании"
description: "Метод для удаления товаров из кампании"
consumes:
- "application/json"
produces:
- "application/json"
parameters:
- in: "body"
  name: "body"
  required: true
  schema:
    type: "object"
    properties:
      client_id:
        type: "string"
        example: "123456-7890123456@advertising.performance.ozon.ru"
      client_secret:
        type: "string"
        example: "xxxxxxxxxxxxxxyyyyyyyyyyyyyyyyyyyyyzzzzzzzzzzzzzzzzzzzzzzz1111111111111222222222"
      campaign_id:
        type: "string"
        example: "1234567"
      sku_list:
        type: "array"
        example: [ "1234567890", "0987654321" ]
        description: SKU товаров
responses:
  200:
    description: "OK"
  400:
    description: "Bad Request"
